# Generated by Django 2.2.12 on 2020-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200416_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='api_key',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
